<?php
function favorites_menu() {
    $items = array();
    $items['favorite'] = array(
        'title' => 'Favorites',
        'page callback' => 'favorites',
        'access callback' => TRUE,
        'type' => MENU_NORMAL_ITEM
    );
    $items['favorite/customers'] = array(
        'title' => 'customers',
        'page callback' => 'customers',
        'access callback' => TRUE,
        'type' => MENU_CALLBACK
    );
    $items['favorite/coffees'] = array(
        'title' => 'coffees',
        'page callback' => 'coffees',
        'access callback' => TRUE,
        'type' => MENU_CALLBACK
    );
    $items['favorite/bagel'] = array(
        'title' => 'bagel',
        'page callback' => 'bagel',
        'access callback' => TRUE,
        'type' => MENU_CALLBACK
    );
    return $items;
}

function favorites() {
    return '
        <ul>
          <li><a href="/favorite/customers">Customers</a></li>
          <li><a href="/favorite/coffees">Coffees</a></li>
          <li><a href="/favorite/bagel">Bagels</a></li>
        </ul>
    ';
}

function customers() {
    return '<ul>
              <li><a href="/customers/Joe">Joe</a></li>
              <li><a href="/customers/Zach">Zach</a></li>
              <li><a href="/customers/Carlos">Carlos</a></li>
            </ul>';
}

function coffees() {
    return '<ul>
              <li>drip<img src='.variable_get("file_public_path", conf_path()."/files/img/drip.jpg").'></li>
              <li>espresso<img src="sites/all/modules/favorites/coffees/drip.jpg"></li>
            </ul>';
}

function bagel() {
    return '<ul>
              <li>everything</li>
              <li>poppy</li>
              <li>egg</li>
            </ul>';
}
