<?php
function cards_menu() {
    $items = array();
    $items['customers/%'] = array(
      'title' => "Stuff",
      'title callback' => 'titleFunction',
      'title arguments' => array(1),
      'page callback' => 'friendsCards',
      'page arguments' => array(1),
      'access callback' => TRUE,
      'type' => MENU_NORMAL_ITEM
    );
    return $items;
}
// function cards_menu() {
//     $items = array();
//     $friends = array('Bob', 'Tim', 'Mike');
//     foreach ($friends as $friend) {
//       $items[$friend] = array(
//         'title' => $friend,
//         'page callback' => 'friendsCards',
//         'page arguments' => array($friend),
//         'access callback' => TRUE,
//         'type' => MENU_NORMAL_ITEM
//       );
//     };
//     return $items;
// }

function titleFunction($arg){
  return $arg;
}

function friendsCards($arg) {
  return '<p>' . $arg . ' is a customer</p>';
}
