<?php
function greeting_menu() {
    $items = array();
    $items['hello_friend'] = array(
        'title' => 'Hello Friend!',
        'page callback' => 'say_hello',
        'access callback' => TRUE,
        'type' => MENU_CALLBACK
    );
    $items['farewell'] = array(
        'title' => 'Farewell Friend!',
        'page callback' => 'say_farewell',
        'access callback' => TRUE,
        'type' => MENU_CALLBACK
    );
    return $items;
}

function say_hello() {
    $user_level = $GLOBALS['user']->roles;
    if(isset($user_level[3])){ //admin view on login
      return "<p>Welcome to the Admin view!</p>";
    }else if (isset($user_level[2])){ //authenticated
      return '<p>Nice to see you!</p>';
    }else if (isset($user_level[1])) { //anonymous
      return "Hello";
    }else {
      return 'thing';
    }
}

function say_farewell() {
    return '<p>Fare thee well my dear friend!</p>';
}

function greeting_user_login(){
    $_GET['destination'] = 'hello_friend';
}

function greeting_user_logout(){
    $_GET['destination'] = 'farewell';
}

function greeting_comment_insert(){
    drupal_set_message("Hi there!");
}
